apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapp
spec:
  replicas: 2
  selector:
      matchLabels:
         app: myjavaapp
         version: 2.6.1
  template:
     metadata:
       labels:
         app: myjavaapp
         version: 2.6.1
     spec:
       containers:
       - name: myjavaapp-container
         image:  maha4iac/myonlinebooking:1
         ports:
         - containerPort: 8080