
apiVersion: v1
kind: Service
metadata:
  name: maha-svc
  labels:
    app: myjavaapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 3001
    protocol: TCP
  selector:
    app: myjavaapp
    