
apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginxrepcon
spec:
  replicas: 2
  selector:
     app: mynginxpod
  template:
   metadata:
   labels:
     app: mynginxpod     
   spec:
     containers:
     - name: mynginxcon
       image: nginx
       ports:
       - containerport: 80
