apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    app: nginxpod
template:
  metadata:
     labels:
       app: nginxpod
  spec:
  containers:
  - name: mynginxcontainer
    image: nginx
    ports:
    - containerport: 80           
