
apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp
spec:
  replicas: 5
  selector:
    app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: nginx
        ports:
        - containerPort: 8080