         
apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginxrc
spec:
  replicas: 5
  selector:
    app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginxcontainer
        image: nginx
        ports:
        - containerPort: 80