apiVersion: v1
kind: ReplicationController 
metadata:
    name: mynginxreplica
spec:
   replicas: 3
   selector:
       app: mynginx
   metadata:
       labels:
         app: mynginx
   spec:
      containers:
      - name: mynginx
        image: nginx
        ports:
        - containerport: 80              
