
apiVersion: v1
kind: ReplicationController 
metadata:
  name: myreplica
spec:
  replicas: 3
  selector:
     app: mynginxpod
  template:
     metadata:
      labels:
       app: mynginxpod
  spec:
     containers:
     - name: myfirstcon
       image: nginx
       ports: 
       - containerport: 80           